spring:
  application:
    name: ${SERVER_NAME:ms-eureka}

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:false}
    fetch-registry: ${EUREKA_FETCH:false}
  instance:
    hostname: ${SERVER_NAME:ms-eureka}
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
  server:
    renewal-percent-threshold: ${EUREKA_RENEWAL:0.80}
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:true}
